### ISSUE TITLE
error: Uncaught (in promise): removeView was not found

### ISSUE THREAD

**Issue by realsaintsteven** [IvanAquino/Ionic-Auth-Starter-with-Laravel-Passport#2]
Thanks for this wonderful code....
When I register a new user, I observed that it imparted my db, but I get this error.
Same as when I tried to Login.
See the sreenshot and code attached

![screenshot 2019-03-07 20 46 03](https://user-images.githubusercontent.com/5979224/53984780-4e4af080-411a-11e9-889b-5b94dd3d0823.png)

`error: Uncaught (in promise): removeView was not found
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at c (http://localhost:8100/build/polyfills.js:3:19461)
    at http://localhost:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)`

**Comment by realsaintsteven** [comment]
POST 
http://127.0.0.1:8100/oauth/token 401 (Unauthorized)
